# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computer_health.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63omputer_health.proto\x12\x03oeo\"C\n\x0e\x43omputerHealth\x12\n\n\x02id\x18\x01 \x02(\r\x12%\n\x04\x64\x61ta\x18\x02 \x02(\x0b\x32\x17.oeo.ComputerHealthData\"\x98\x01\n\x12\x43omputerHealthData\x12\x11\n\theartbeat\x18\x01 \x02(\r\x12\x1e\n\x16vehicle_script_running\x18\x02 \x02(\x08\x12\x1a\n\x12\x65vm_script_running\x18\x03 \x02(\x08\x12\x17\n\x0f\x63pu_utilization\x18\x04 \x02(\x02\x12\x1a\n\x12memory_utilization\x18\x05 \x02(\x02')



_COMPUTERHEALTH = DESCRIPTOR.message_types_by_name['ComputerHealth']
_COMPUTERHEALTHDATA = DESCRIPTOR.message_types_by_name['ComputerHealthData']
ComputerHealth = _reflection.GeneratedProtocolMessageType('ComputerHealth', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERHEALTH,
  '__module__' : 'computer_health_pb2'
  # @@protoc_insertion_point(class_scope:oeo.ComputerHealth)
  })
_sym_db.RegisterMessage(ComputerHealth)

ComputerHealthData = _reflection.GeneratedProtocolMessageType('ComputerHealthData', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTERHEALTHDATA,
  '__module__' : 'computer_health_pb2'
  # @@protoc_insertion_point(class_scope:oeo.ComputerHealthData)
  })
_sym_db.RegisterMessage(ComputerHealthData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMPUTERHEALTH._serialized_start=30
  _COMPUTERHEALTH._serialized_end=97
  _COMPUTERHEALTHDATA._serialized_start=100
  _COMPUTERHEALTHDATA._serialized_end=252
# @@protoc_insertion_point(module_scope)
