# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radio_information.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17radio_information.proto\x12\x03oeo\"G\n\x10RadioInformation\x12\n\n\x02id\x18\x01 \x02(\r\x12\'\n\x04\x64\x61ta\x18\x02 \x02(\x0b\x32\x19.oeo.RadioInformationData\")\n\x14RadioInformationData\x12\x11\n\tcompliant\x18\x01 \x02(\x08')



_RADIOINFORMATION = DESCRIPTOR.message_types_by_name['RadioInformation']
_RADIOINFORMATIONDATA = DESCRIPTOR.message_types_by_name['RadioInformationData']
RadioInformation = _reflection.GeneratedProtocolMessageType('RadioInformation', (_message.Message,), {
  'DESCRIPTOR' : _RADIOINFORMATION,
  '__module__' : 'radio_information_pb2'
  # @@protoc_insertion_point(class_scope:oeo.RadioInformation)
  })
_sym_db.RegisterMessage(RadioInformation)

RadioInformationData = _reflection.GeneratedProtocolMessageType('RadioInformationData', (_message.Message,), {
  'DESCRIPTOR' : _RADIOINFORMATIONDATA,
  '__module__' : 'radio_information_pb2'
  # @@protoc_insertion_point(class_scope:oeo.RadioInformationData)
  })
_sym_db.RegisterMessage(RadioInformationData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RADIOINFORMATION._serialized_start=32
  _RADIOINFORMATION._serialized_end=103
  _RADIOINFORMATIONDATA._serialized_start=105
  _RADIOINFORMATIONDATA._serialized_end=146
# @@protoc_insertion_point(module_scope)
